name: Build All Mods

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore "Cosmo Mod Library.sln"

    - name: Build Solution
      run: dotnet build "Cosmo Mod Library.sln" -c Release

    - name: Package Mods
      run: |
        powershell Compress-Archive -Path artifacts/* -DestinationPath todos-os-mods.zip

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: mods-prontos
        path: todos-os-mods.zip
